### ISSUE TITLE
Move-insert does not work in VS2015.

### ISSUE THREAD

**Issue by hypernewbie** [mattreecebentley/plf_colony#1]
Documentation claims:
"However, if only move-insert and/or emplace are utilized to insert elements into the colony, T is only required to meet the requirements of Erasable."

I can't get this to actually work.

Repro steps:
1. Make a class.
2. Delete both its copy constructors.
3. Try to emplace onto a colony of the class

MSVC compiler will complain about accessing private function (deleted constructors). When removing the two lines that delete the two copy constructors, code compiles.

**Comment by hypernewbie** [comment]
https://github.com/mattreecebentley/plf_colony/pull/2
MinGW / G++ complains about the same.

**Comment by mattreecebentley** [comment]
I noticed the pull request and subsequent closure - is this still a bug?
The first thing to check is that this is not a derived class-
if it is, C++ will call the base's copy constructor (more information 
here: 
http://stackoverflow.com/questions/8888268/why-explicit-call-of-base-move-constructor-actually-calls-base-copy-constructor)

Also, colony's emplace function is literally "return 
insert(std::move(element_type(std::forward<Arguments>(parameters)...)));", 
which is pretty clear I think - if it fails, it may be a bug in MSVC.
Matt

**Comment by hypernewbie** [comment]
It is still at least a documentation problem. the docs should say that the object needs to be Movable, not only Erasable.

The problem doesn't affect my use case any more, making the objects movable is not an issue for me.

**Comment by mattreecebentley** [comment]
True. Thanks for this, have updated-
