### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by zamazan4ik** [mattreecebentley/plf_colony#10]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers. For making a package you should make release of the library and then write a simple script.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by mattreecebentley** [comment]
Hey there-
will look into this, I don't know much about conan at this stage.
What advantage is there to putting this into a conan package, when colony is just a single header file BTW?

**Comment by mattreecebentley** [comment]
BTW someone has a written a conan package for colony here:
https://github.com/alaingalvan/conan-plf-colony
I assume it's still valid, although 2 years old.
