### ISSUE TITLE
if in blank() should be constexpr

### ISSUE THREAD

**Issue by CaptainCrowbar** [mattreecebentley/plf_colony#20]
MSVC 2017 with `/W4 /WX` complains about the constant condition on line 1039 of `plf_colony.h`. It suggests changing the plain `if` to `if constexpr`, and I agree.

**Comment by mattreecebentley** [comment]
I tried all that.
(a) It makes no difference to performance, (b) some compilers don't support constexpr and it's a pain to maintain and (c) MSVC2017 doesn't fully support constexpr yet, despite it's warning at W4, which is the reason why it hasn't been implemented.

**Comment by mattreecebentley** [comment]
Ended up implementing constexpr across the board, as it turns out MSVC have fixed their previous constexpr issues, but mainly cause it allowed me to fix a problem with moveable-but-non-copyable types.
