### ISSUE TITLE
Add cmake file and "standard" project layout

### ISSUE THREAD

**Issue by Mike-Devel** [mattreecebentley/plf_colony#21]
I know, this probably seems overkill for a single header library, but have you considered adding a simple cmake file that provides a Plf::cplony target and maybe to adopt a project layout that puts the header files in a subfolder with the name of your library (as much as such a thing exists?) Specifically I'd put the code into `<project-root>/include/plf/colony.h` or `<project-root>/plf/colony.h`.

The idea behind it isn't that it would make using plf_colony much simpler than it already is (but also not harder) it is just that this way, one can use all dependencies in a similar fashion, regadless, of how big or small they are or how complicated their project structure is:

I could e.g. just use

    target_link_libraries( my_target PULBIC 
            Boost::filesystem
            Plf::colony
            Catch2::Catch2     
           ... other dependencies      
    ) 

to my cmake script and

     #include <boost/filesystem/fstream.hpp>
     #include <plf/colony.h>
     #include <catch2/catch.hpp>
     #include <lib/file.h>

to my c++ code.

**Comment by mattreecebentley** [comment]
Yeah, definitely not. People have all sorts of layouts and configs for their projects.

**Comment by Mike-Devel** [comment]
What about the cmake file?

**Comment by mattreecebentley** [comment]
ps. if you want to make a cmake setup and have it linked to in readme.md in the same way that the conan package currently does, happy to do that, provided setup doesn't include colony code.

**Comment by Mike-Devel** [comment]
Thanks, but if the cmake file is not part of the repository containing the code, I don't see the point. We'll just use our own fork with our standard project layout and cmake file.

**Comment by mattreecebentley** [comment]
*shrug*
Up to you.
