### ISSUE TITLE
Question about shrink_to_fit implementation

### ISSUE THREAD

**Issue by freak82** [mattreecebentley/plf_colony#22]
Hi there,

First, thanks for the library.

I'm trying to use the `plf::colony` with move only elements and I stumbled upon compilation error when invoking `shrink_to_fit` and more precisely the `consolidate` function. As far as I understood the implementation it uses the copy constructor of container to shrink it and then move it back to `*this`. I understand that the reusing of the copy constructor simplifies the implementation here but want to ask would it be a problem the 'alive' entries to be moved instead of being copied?

Regards,
Pavel.

**Comment by mattreecebentley** [comment]
I take it you mean moving the elements directly into the new colony first, then moving the new colony to *this?
Yes, it's certainly doable.
Just out of interest, what move-only elements do you come across? I haven't encountered any in my work.

**Comment by mattreecebentley** [comment]
Anyway, fixed - will default to move if type traits are supported by the compiler, and type is moveable.

**Comment by freak82** [comment]
Hi again,

Thanks for the addition.

I just want to let you know that it still doesn't compile for move-only types - https://godbolt.org/z/aJ6f-B.
It seems to me that it fails because when instantiating the code in `consolidate` function the compiler still 
compiles the branch with `temp.insert(begin_iterator, end_iterator);` and so it still requires the element to have copy constructor/assignment. However, this branch seems to be later discarded by the compiler and so adding copy constructor/assignment to the element without defining them workaround the issue and the code compiles and links fine.

**Comment by mattreecebentley** [comment]
Ah right - hadn't thought of that. Unfortunately there still needs to be
allowance made for types which aren't movable but which are copyable, but
I'll look into what can be done, if anything.

**Comment by mattreecebentley** [comment]
p.s Can you try replacing the following line 2158:
if (std::is_move_assignable<element_type>::value && std::is_move_constructible<element_type>::value)

with
if constexpr (std::is_move_assignable<element_type>::value && std::is_move_constructible<element_type>::value)

And see whether that makes a difference? I'm unsure at what stage constexpr kicks in during compilation, whether it's before or after type-checking, so I'm unsure whether it'll make a difference.

**Comment by freak82** [comment]
It compiles fine with with the proposed change. I'm working with g++ 7.3 and `-std='c++17'`.
So, the proposed solution will work for people which use C++17 (due to `if constexpr`).
I'm not sure which standard the library targets.

**Comment by mattreecebentley** [comment]
That's what I thought. I've constexpr'd it all, it's just been a matter of waiting until MSVC fixed their bugs (which they have). Will upload the new version some time today - thanks for making me aware of that.
