### ISSUE TITLE
MSVC Warning about usage of `freopen`

### ISSUE THREAD

**Issue by Klaim** [mattreecebentley/plf_colony#28]
The Build2 package of PLF-Colony is published on https://cppget.org which have a CI system which regularly builds the package with new setup. See for example: https://cppget.org/plf-colony/5.11.0

On all builds related to msvc, there is this warning which seems to be serious:

```
plf_colony_test_suite.cpp(236): warning C4996: 'freopen': This function or variable may be unsafe. Consider using freopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h(243): note: see declaration of 'freopen'
```

I'm not totally sure if replacing the call by `freopen_s` would be the best solution here, in particular if that line is supposed to compile on several platforms. Maybe making a local version would work?

**Comment by mattreecebentley** [comment]
It's not serious. It's MS advertising their own platform-specific more-secure functions. They do this quite a bit.
They also complain about use of uninitialized_copy in plf::list.
Thankfully here it's just the test code, not the .h that causes warnings.

**Comment by Klaim** [comment]
> It's not serious. It's MS advertising their own platform-specific more-secure functions. They do this quite a bit.

While I see your point, it's actually part of C11 standard, see: https://en.cppreference.com/w/c/io/freopen
Depends on what C or C++ standard you want to target, I would say. (C++11 does not depends on C11 but C++17 does, and my package currently requires C++17 as a minimum).

For now I will ad the define to disable these warnings. Feel free to ping me if you ever decide to use the _s variant so that I can remove the disabling (I understand it will probably never happen haha).

**Comment by mattreecebentley** [comment]
Ah I see - I'm so used to MS advertising their own versions of things I didn't stop to think that it might be an actual function. Still, it's a warning not an error. And it will stop pre-c++11 compilers from running the code, which isn't great for my testing regime (which is what that script is for). WIll have a think on it.

**Comment by Klaim** [comment]
Yes the warning is for security concerns and is not a deprectation (not like https://queue.cppget.org/plf-colony/5.11.0+1/log/windows_10-msvc_15.9/public/0.11.0/update - not sure why it happens only with VS2017, investigating) so it's not a problem to ignore it in tests.
Here is the package with the warning disabled: https://queue.cppget.org/plf-colony/5.11.0+1
