### ISSUE TITLE
MSVC warning: usage of feature deprecated in C++17

### ISSUE THREAD

**Issue by Klaim** [mattreecebentley/plf_colony#29]
Not a blocking issue, just a heads-up about C++17 `deprecated` warning that might be important if you want plf-colony to work in future C++ versions:

```
C:\tmp\build\plf-colony-5.20.0\plf_colony\upstream\plf_colony.h(4021): warning C4996: 'std::allocator<unsigned char>::pointer': warning STL4010: Various members of std::allocator are deprecated in C++17. Use std::allocator_traits instead of accessing these members directly. You can define _SILENCE_CXX17_OLD_ALLOCATOR_MEMBERS_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\xmemory0(889): note: see declaration of 'std::allocator<unsigned char>::pointer'
C:\tmp\build\plf-colony-5.20.0\plf_colony\upstream\plf_colony.h(4020): note: while compiling class template member function 'plf::colony<small_struct_non_trivial,std::allocator<element_type>,unsigned short>::raw_memory_block_pointers::~raw_memory_block_pointers(void)'
        with
        [
            element_type=small_struct_non_trivial
        ]
C:\tmp\build\plf-colony-5.20.0\plf_colony\upstream\plf_colony_test_suite.cpp(1797): note: see reference to function template instantiation 'plf::colony<small_struct_non_trivial,std::allocator<element_type>,unsigned short>::raw_memory_block_pointers::~raw_memory_block_pointers(void)' being compiled
        with
        [
            element_type=small_struct_non_trivial
        ]
C:\tmp\build\plf-colony-5.20.0\plf_colony\upstream\plf_colony_test_suite.cpp(1143): note: see reference to class template instantiation 'plf::colony<small_struct_non_trivial,std::allocator<element_type>,unsigned short>::raw_memory_block_pointers' being compiled
        with
        [
            element_type=small_struct_non_trivial
        ]
```

This happen with all the msvc versions starting with `Visual Studio 15 (2017) Update 9 (15.9.3)`.
For more details, see: https://queue.cppget.org/plf-colony/5.20.0/

What solution do you prefer?
 - assume that plf-colony is C++17 only and remove the deprecation warnings (I'll do it in the package setup if you prefer this);
 - try to make it future-proof by using `std::allocator_traits` as suggested (I can try a patch but suspects it should be better handled by you).

For course solution 1 is the simplest, I just want to be sure if it's ok with you.

**Comment by mattreecebentley** [comment]
This is a bug in MSVC which has been reported to them, it uses allocator_traits at all times if it's available. 
I might remove the code in question though because it was an experimental feature and I'm not sure it'll be of use to anyone. Waiting on feedback. If you have any opinions let me know.

**Comment by Klaim** [comment]
I don't have much opinion.
I think I will remove the warning for this version only (5.20), make sure that the following versions don't remove the warning so that I can check that later, and assume that you will remove the feature anyway.
Seems reasonable?

**Comment by mattreecebentley** [comment]
Lets see whether MS fixes the bug first - 
I need to do some benchmarking to establish the worthiness of the function, so we'll see with that as well. Whatever you need to do is okay by me.

**Comment by Klaim** [comment]
Ok, for now I'll add the flag to not have the warning and remove it between each version so that I can check if it have been fixed later.

**Comment by mattreecebentley** [comment]
MS pointed out it's a result of MSVC non-compliance in default (permissive) compilation mode.
Have fixed, although its more of a workaround really.
https://developercommunity.visualstudio.com/content/problem/678206/false-warning-msvc2019-reports-use-of-stdallocator.html?childToView=691395#comment-691395

**Comment by Klaim** [comment]
Nice, I'll check that the 5.21 build2 package does not hide the warning and still don't show the warning as soon as I find the time 👍
