### ISSUE TITLE
Make erased_locations an intrusive linked list 

### ISSUE THREAD

**Issue by ratchetfreak** [mattreecebentley/plf_colony#3]
`erased_locations` is used as a set of blocks that were freed but is external to the colony which requires a cache miss to get a erased block. 

Instead you can store a next pointer in the deallocated element and have a stored_element_type to the last deallocated element

``` C++
union union_element_type {
    element_type el, 
    stored_element_pointer_type next;
}
typedef union_element_type* union_element_pointer_type

iterator erase(const iterator &the_iterator)
{
    //...

    //instead of pushing onto erased_locations and after destructor
    the_iterator.union_element_pointer->next = first_erased_element_pointer;
    first_erased_element_pointer = the_iterator.union_element_pointer;

    //...
}

iterator insert(element_type &&element)
{
    //...

   //instead of popping of erased_locations
   iterator new_location;
   new_location.element_pointer = first_erased_element_pointer;
   first_erased_element_pointer = first_erased_element_pointer->next;
   PLF_COLONY_CONSTRUCT(...);

   //...
}
```

**Comment by mattreecebentley** [comment]
You're talking about a 'free list', essentially - the issue with that is that colony elements are not guaranteed to be large enough to store a pointer, but even if they were, stack popping doesn't involve a cache miss. Also having a free list would slow down erase when it comes to removing an empty colony group and subsequently removing erased elements from the group from the collection of erased element locations.
Incidentally in current beta the internal stack is not an external class.

**Comment by mattreecebentley** [comment]
Hi there- in case you're interested, I ended up doing this, essentially, though in a very different way to what was described here:
https://plflib.org/blog.htm#colony5changessummary
https://plflib.org/blog.htm#colony45
