### ISSUE TITLE
reserve() calls constructor of T (C++17)

### ISSUE THREAD

**Issue by degski** [mattreecebentley/plf_colony#34]
As per above, `plf::colony::reserve ( )` calls constructor of `T` (I am using C++17).

Why, I read about that `T` needs to be `Copy-Constructable`, but if it is to do a reserve, I'm a worried. The `T`'s are never moved (re-allocated), in C++03 maybe?

I've been wrapping `plf::colony` and in my `T` there are some `std::atomic` s, using proper move construction and propagation, these atomics have been no problem in the implementation of my class emplace/push/pop type of functionality, except bizarrely `reserve()`.

I've written most of what constitutes a lock-free stack (on top of `plf::colony`). I would like to build on top, a circular list, so concurrent insertions and removals are possible as all changes will be local, hence the need for the address of the first `T` to be allocated node. 

I would like to find the address of the first `T` that will be allocated, so I thought to `reserve()` and scour the raw data, to obtain the address of the first 'T' (logically it should be there somewhere, help welcome?), by-passing construction. If want my type to have erasable as requirement only, so doing a quick default emplace/erase, immediately would make my type have a default-constructable requirement, i.e. that's not acceptable.

**Comment by mattreecebentley** [comment]
*shrug*
Current implementation is that multiple spare empty blocks aren't allowed,
which means that in order to reserve in a colony that isn't empty, it generally needs to reallocate existing data to new blocks in order to increase capacity.
I did do an implementation in the past that allowed reserved empty blocks but the extra code Required in insert meant that overall performance dropped by 2% in general real-world benchmarks.
However, I am looking at refactoring to allow reserve to be "new blocks only and no reallocation", in order to get the project ready for standardisation attempts, so stay tuned.
This may change soon.

**Comment by degski** [comment]
> shrug

Well maybe, but it's definitely surprising. In the meanwhile I figured out, that I have to write the lock-free-circular list as a ~doubly~ singly linked list (to get the concurrency right), which reduces everything to `the problem of the first node`, which I've now solved by adding more api to my class, instead of reserving. As long as I don't touch the storage of colony, `plf::colony` seems to work also with non-copyable types (in C++11 and up).

I think you should put on your web-site that `reserve()` is non-compliant.

PS: I would love to see this standardised, I'm happy to contribute if I can, just yell, like testing something or anything.

**Comment by mattreecebentley** [comment]
... like I said, it's due to change. There are no standards-driven templates for reserve(), so the current implementation is not non-compliant with anything, but certainly it is "out of character" with what the other containers do. I'll let you know when I have a beta :)

**Comment by degski** [comment]
I was reading: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2137r0.html#simplicity In the paper it's suggested that a funny `reserve()` like this one should simple not be called `reserve()`, but otherwise has (implicitly) the full right to exist (just don't call it `reserve()` (`extend()` f.e.), it simply implies that currently '`reserve()` has not yet been implemented for `plf::colony`' (but something similar for a limited number of types is supplied instead).

**Comment by degski** [comment]
@mattreecebentley I've solved the (my) problem generically with a solution that will allow me to reserve (after default construction only, which is the most important, I'll just ignore reserve requests if the size > 0) as well, by defining the below class as T of `plf::colony`:

    template<typename U>
    struct uninitialized_value_type {
        using value_type = U;
        alignas ( value_type ) char _[ sizeof ( value_type ) ];
        uninitialized_value_type ( ) noexcept                                  = default;
        uninitialized_value_type ( uninitialized_value_type const & ) noexcept = default;
        uninitialized_value_type ( uninitialized_value_type && ) noexcept      = default;
        [[nodiscard]] uninitialized_value_type & operator= ( uninitialized_value_type const & ) noexcept = default;
        [[nodiscard]] uninitialized_value_type & operator= ( uninitialized_value_type && ) noexcept = default;
    };

I then later (in the containing [of `plf::colony`] container) new-place into the empty space.

**Comment by mattreecebentley** [comment]
Reserve will be removed in the next version of colony.

**Comment by mattreecebentley** [comment]
Actually, I left it in - the reason for removal was the full reserve caused severe performance loss, however this turned out to be a bug in gcc9 and gcc10:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96750
