### ISSUE TITLE
get_iterator_from_pointer expects a non-const pointer

### ISSUE THREAD

**Issue by VaderDev** [mattreecebentley/plf_colony#37]
As it is even documented get_iterator_from_pointer expects a non-const pointer forcing a const_cast in some cases.

```
plf::colony<int> colony;
const int* ptr = &*colony.insert(0);
colony.get_iterator_from_pointer(const_cast<int*>(ptr));
                                 ^^^^^^^^^^^^^^^^
```

However looking at the implementation (as expected) the pointed (object) data is not accessed therefore a const pointer should be sufficient.

(Please, also consider another function overload for `erase` with a single pointer as argument which internally calls get_iterator_from_pointer just for convenience.)

**Comment by mattreecebentley** [comment]
The construction of the return iterator forces a const cast to non-const as the iterator has to use a non-const pointer internally for obvious reasons. I can shift the const_cast there, but then, where's the benefit?

I won't do an overload for erase with pointers as people need to understand there's a cost involved in conversion and also the current implementation reflects the standard library proposal, which would not permit that function.

**Comment by VaderDev** [comment]
I see, valid points.

My main concern was a const_cast in client side code which was hard to reason about.
You are correct, returning a non-const iterator to an object that was specified with a const pointer could be misleading.

What about a second overload? With `const_iterator` for `const pointer` beside the current non-const for the non-const one?
```
iterator get_iterator_from_pointer(const pointer element_pointer) const PLF_NOEXCEPT;
const_iterator get_iterator_from_pointer(const const_pointer element_pointer) const PLF_NOEXCEPT;
```
This would be semantically correct and would allow the client side code to erase an element with a const pointer without the need for a const_cast.

**Comment by VaderDev** [comment]
And thus this became a duplicate of #32 (sorry, didnt noticed sooner)
I would still argue beside that this function as this is nothing like any std:: container's functionality but I will close the issue as it has already been responded in the past.

Thank you very much for the library and your work on the standardization!

**Comment by mattreecebentley** [comment]
Thanks for that. What are you using colony in btw? Currently trying to get community feedback on production work they're using it in, for the standardization effort.
In terms of get_iterator_from_pointer, this will be one of the questions I ask LEWG.
The overall leaning of std:: seems to be to provide as small an interface as possible in order to reduce implementation effort.
I will put in the second overload you talked about into the implementation for the moment and see where that goes.

**Comment by VaderDev** [comment]
Thank you, I think the const overload makes perfect sense and provides a more complete API and helps with correctness, the implementation is also trivial.

The usage is for a custom game engine and for a GUI library but both of them are still in early development so the experience is limited, but Colony is used as backend for multiple ECS like systems.

**Comment by mattreecebentley** [comment]
Thanks for that - also, out of interest what prevented you from simply putting in the const conversions in the client-side code?

**Comment by VaderDev** [comment]
Nothing really, I just like to be really really really pedantic and const_cast was not logical for an erasure operation and I thought it might worth the feedback.
