### ISSUE TITLE
get_iterator_from_pointer() returns valid iterator for invalid pointers

### ISSUE THREAD

**Issue by MarcKamradt** [mattreecebentley/plf_colony#4]
You can just call `get_iterator_from_pointer( (T*) 0x13370000 )` and the method will not return `end()` but a valid iterator.

**Comment by MarcKamradt** [comment]
Nevermind. I just found out that the VS2015 compiler did not emit any assembly code for the assert() I had in place to catch this case. So I figured it must have not returned `end()`.

I wonder how that is possible in a debug build...

**Comment by mattreecebentley** [comment]
Anything's possible with MS! :)
