### ISSUE TITLE
[Feature request] Consider adding push/emplace_back() proxies.

### ISSUE THREAD

**Issue by Convery** [mattreecebentley/plf_colony#40]
Was recently playing around with `plf::colony` (it's great) and wanted to update some utilities to use it instead of `std::vector`. While `insert()` covers the functionality needed, consider adding proxies for it matching the `std::vector` methods so that other developers can search and replace in their codebases.

**Comment by mattreecebentley** [comment]
Hiya, I think invalidates the current assumptions about the container (insertion implacement is considered unordered, random). If we start giving the option to do that, it means people with a low understanding of how the container functions will end up using it, not realising that this reduces iteration peformance and cache locality.
I'm interested in any other thoughts you have on the subject, but I think this is probably a no-go.
