### ISSUE TITLE
Erase is faster than Clear

### ISSUE THREAD

**Issue by Meerkov** [mattreecebentley/plf_colony#42]
Seemingly contrary to STL containers, colony.clear() is slower than colony.erase(colony.begin(),colony.end()).

Maybe I'm alone in being surprised that .clear() deallocates the memory, which seems to go against the purpose of the colony container.

**Comment by mattreecebentley** [comment]
Hi there-
you're right, clear shouldn't deallocate, this is a holdover from when colony didn't have a multi-block reserve function. Will fix.
Appreciate some input on which strategy is best for retaining blocks. In the case of a non-reserved colony that's simply been filled with singular insertions, there will be some small blocks at the front. From a iteration performance perspective, it's not great to retain these. Therefore a better strategy might be to only retain the final block, and any other blocks which're == max_block_capacity_limit, rather than all blocks.
However I'm not sure what you're basing the assumption that erase is faster than clear on?

**Comment by Meerkov** [comment]
The particulars of the test are specific to my setup, but in summary: 

I was creating 1 object then clearing. Repeat this thousands of times. I checked my performance analyzer, and noticed that the colony was spending time deallocating in the clear function, so I changed to erase to avoid it. This resulted in a speedup.

**Comment by mattreecebentley** [comment]
That's strange. Erase will also deallocate the blocks as soon as they become empty, so there should not be a speedup.
[edit: just remembered erase will retain some blocks if they meet certain criteria. Will likely apply the same criteria to clear - still interested in your input there]

**Comment by Meerkov** [comment]
Currently my actual CPU code is very thin, so the deallocation of the colony was maybe 20% of the total runtime. So even minor differences in how they are written could have been resulting in some speedup when changing between them even if they do similar things. Looks like my current code using erase shows it is taking about 11% of my loop.

**Comment by Meerkov** [comment]
I believe the speedup I'm seeing is because I'm utilizing colony as an object pool. So deallocating memory results in a lot of churn as objects need to be reallocated instead of just re-initialized.

Currently, my loop takes about 1.5 seconds, with colony.erase taking 8% of that.  If I switch back to colony.clear(), my runtime increases to 2.5 seconds.

**Comment by mattreecebentley** [comment]
Fixed now, should be better than erase, retaining all blocks for moment, original clear() functionality (deallocate all blocks) moved to reset(), also can follow clear() with shrink_to_fit().

**Comment by dumblob** [comment]
As a close up - could you @Meerkov maybe provide your code (or relevant parts) as an interesting benchmark to show case in the readme of this repository?

**Comment by Meerkov** [comment]
Hmm, well I'd like to show some benchmarks, but I can't recall how I had the code before.

Here is an outline of my ObjectPool class. Outside of this code I do the following:
1) Create an ObjectPool. Using getOne() to get an free object pointer, initialize an object. Get and initialize a second object, then call clear().
2) Use getOne() to get a free object, initialize it, then call clear().
3) Repeat step 2 about 1000 times.
4) Delete the ObjectPool.
5) Go back to 1. Repeat 5000 times (so you can more easily benchmark).

```c++
template <typename T>
class ObjectPool {
	std::vector<T*> pool;

public:
	
	plf::colony<T> i_colony;

	T* getOne() {
		if (pool.size() == 0) {
			auto itr = i_colony.insert(T());
			return static_cast<T*>(&(*itr));
		}

		auto x = static_cast<T*>(pool.back());
		pool.pop_back();
		x->clear();
		return x;
	}

	void release(T* obj) {
		pool.push_back(obj);
	}

	void clear() {
		pool.clear();
		i_colony.erase(i_colony.begin(), i_colony.end());

                // Previous Slow Version: (to the best of my memory)
                // pool.clear();
                // for(auto& i: i_colony) {
                //     release(&i);
                // }
                // i_colony.clear();
	}
```

Worth noting, after the fix discussed in https://github.com/mattreecebentley/plf_colony/issues/42#issuecomment-869277695 is used, this speed difference might disappear.
