### ISSUE TITLE
PLF_CPP20_SUPPORT shouldn't be defined on Android NDK r24

### ISSUE THREAD

**Issue by mikezackles** [mattreecebentley/plf_colony#46]
As best I can tell, this detection is broken for the Android NDK, which ships with a copy of libc++ that does not implement the `concepts` header. Maybe it would be appropriate to use `_LIBCPP_VERSION`? There doesn't appear to be a way for users to override this behavior without patching.

**Comment by mikezackles** [comment]
For what it's worth, the relevant NDK issue is android/ndk#1530. They are shipping a libc++ that's something like 2 years out of date compared to the version of clang they're shipping.

**Comment by mattreecebentley** [comment]
Hey Zachary,
thanks for getting back to me on this,
I'm currently busy on the hive (C++ standards version of colony) 
implementation, but once done there (probably a month to go) will do this.
Cheers!
Matt

**Comment by mikezackles** [comment]
No problem -- no rush from me. Love the lib. Thanks!

**Comment by mattreecebentley** [comment]
I think this is fixed now - please check for me-
