### ISSUE TITLE
Adding functionality discussion

### ISSUE THREAD

**Issue by dokipen3d** [mattreecebentley/plf_colony#47]
Hiya, the repo doesn't seem to have discussion so hopefully opening an issue isn't too offensive. If so, we can take the discussion elsewhere.

I've found it useful to be able to add some functionality to colony that allows me to get extra information about where in the colony the data is stored.

Specifically,  I've added 3 things.

1) a Groups() function to colony that returns a std::vector of group pointers. 

```
    std::vector<colony::group*> groups() const {
        std::vector<colony::group*> _groups;

        for (group_pointer_type current_group = begin_iterator.group_pointer;
             current_group != end_iterator.group_pointer;
             current_group = current_group->next_group) {
            _groups.push_back(current_group);
        }

        _groups.push_back(end_iterator.group_pointer);

        return _groups;
    }
```

2) and 3)
Two functions to the colony iterator. group_ptr() and local_offset().

group_ptr() returns a pointer to the current group that the element pointed to by the iterator is stored in. 

local_offset is essentially an int that is an offset into the local storage in that group.

```
inline group_pointer_type group_ptr() const PLF_NOEXCEPT {
    return group_pointer;
}

inline typename colony::difference_type localOffset() const PLF_NOEXCEPT {
    return element_pointer - group_pointer->elements;
}
```

The reason this is useful is because I can use colony as a backing storage for another data structure in this case an unordered_map, where the key is a 3d integer coordinate and the value is a group/offset pair. This way I can spatially look up a 3d coordinate location and get back the colony group and local offset and index into it.

```
auto groups = mycolony.groups();

for (auto it = coordToTilemap.cbegin(); it != coordToTilemap.cend(); ++it) {
    auto gp = groups[it->second.group_pointer->group_number];
    doSomethingWithData((*gp)[it->second.offset].data());
}
```
I think this is useful because I can still iterate directly over the colony but also have a custom 'view' over the data.

Keen to see what others think of this.

**Comment by mattreecebentley** [comment]
Hi Daniel,
the data() function (https://plflib.org/colony.htm#functions) gives you the first bit, but without the std::vector #include overhead,

Regards second bit, for an unordered map, why would you not simply store a pointer? That's smaller and faster than a group/offset pair.

**Comment by dokipen3d** [comment]
For the vector, I think I added it so that it was more convenient to run an openmp parallel for loop over the groups. If you want to keep vector out, I can probably just have my own helper function to do that.

For the group/offset pair, the reason was because I am using multiple colonies to store multiple channels of data that share the same count/layout. In this case it would be a float channel for "density" data and a glm::vec3 channel for velocity. I would like them to be accessed with the same index but stored separately (SOA vs AOS etc..).

What I'd like to explore eventually (when I get a block of time) is see how to have a colony of multiple types (like EASTL's tuple_vector) so colony<float, float, vec3, vec3> etc  and have the benefits of the group/chunks like reusing slots and single skipfield but with multiple contiguous allocations for each type. I may have asked about this before but I paused on this project last year and now revisiting.

Another possibility is to use boost::pfr to do the reflection/deconstructing of the members of a simple struct for me and we can then have a colony of a simple struct and a tag to indicate that you want SOA layout so do that transformation.

I'm aware this is all very hand wavy but its all part learning for me.

**Comment by mattreecebentley** [comment]
I think unfortunately this is a bit too use-case-specific to be of generic usage (but feel free to try and convince me otherwise). I would be inclined, if I were writing the code, to just fork it and make the iterator member variables public, to save time.
In terms of vector, keeping it out is necessary in order to not drag in a ton of codebases just because someone included colony in a project. Most STL vector implementations drag in a lot of shared code.

The advantage of the 'data' function is that it also gives you bitfields to check for erased elements. If you're not erasing elements there is probably a better way of doing this, as you're wasting cache space on the skipfields.

**Comment by mattreecebentley** [comment]
I do like your idea of having a kind of SOA setup with colony though - 
that's only a potential optimisation if each stack of data is being iterated over separately.
But that's a potentially useful fork I could be interested in working with you on.

But, as you say, if the info is tied and stuff is being erased, then you save some space on the skipfield.
