### ISSUE TITLE
Update conan link in homepage

### ISSUE THREAD

**Issue by SpaceIm** [mattreecebentley/plf_colony#48]
The conan package mentioned in the homepage is very old and not part of the official public repository of conan (conancenter).

Actually, a conan recipe of plf_colony is available in conancenter: https://conan.io/center/plf_colony

You should advice to use this one since it has far more chance to be kept uptodate.

Moreover, it would be nice to publish official releases on github as well, so that package maintainers can be quickly notified, and therefore it gives you more chance to see your library properly maintained in package managers.

**Comment by mattreecebentley** [comment]
Cool thanks.
The problem with publishing 'releases' is that every commit is a release. I don't use github as anything other than a publishing platform. I know lots of github users do it this way, though it's not the most common way to use github.

**Comment by Klaim** [comment]
About that, to be clear: it's problematic that you don't release versions as tags because it makes any automation of packaging from hard to impossible through github.

I stopped updating `build2` packages because of this, as it's impossible to get only notifications for releases without releases being tags, and it became either conbersome to check the repo every now and then or to have to receive all irrelevant notifications. 
I don't think tagging a version is hard at all, it's one command that you could do at the same time as making the commit, and it would automatically notify anyone/thing waiting for releases to trigger some script to do some work. It also makes github publish archives automatically for you. Basically it makes life simpler for every user.
That there is one tag per commit is not an issue at all, it's exactly like if you had a hidden development branch and main/master is the "released" branch.

Anyway that's just my opinion.

**Comment by mattreecebentley** [comment]
Every user, except for me. I upload manually, because git tools are cumbersome and don't work well with my workflow. So every release tag would be manual.
We've covered this:
https://github.com/mattreecebentley/plf_colony/issues/41#issuecomment-869280986

Did you try any of the solutions in that post?

**Comment by Klaim** [comment]
Yes, the first link suggested in that issue comment is not an official github service and therefore is not reliable. Right now it doesn't even respond (basically,  it's dead). There are others like that and they cannot be reliable if it's not provided by github themselves or imply having to link an (online) app to your github account. But nobody will do that just to track releases as there is already a system...
The second solution suggests is to use a RSS feed aggregator only to handle this package, which is, as I said before, cumbersome and problematic in many ways (like there is no way to differentiate when you actually add a commit that's a quickfix not changing the version but just the package (what in `build2` we call a package "revision") - and that did happen).

Also about (from that issue):
> looks like I'd have to create a new release for every single commit, otherwise people would assume non-release-tagged versions are beta. I don't want to do that.

and (from here):
> Every user, except for me. I upload manually, because git tools are cumbersome and don't work well with my workflow. 

Releases are automatically created for you for each tag you push. Just `git tag v7.0.0` and `git push --tags` and you're done. That just 2 lines more than `git commit ...` and `git push` and if you use VS code or any other IDE they have ways to do it with one click. I think you could even make a small script that "commit, tag and push" with a input variable for the tag name (I have done that in the past, but using `build2`, it does that automatically for me too).

As said, having one tag per commit in the main branch is standard when we have separate branches for development and the main (or master) branch being the "released" branch, except that here development happens privately on your side (which is fine). So you're covered there.

Whatever the way you go, if you can at least tag the new major version (as you mentioned in the pointed issue) I'll package it soon. 👍🏽

**Comment by mattreecebentley** [comment]
As I said, I don't use git to upload, I upload manually. I'd appreciate it if you stop pushing this, as I have a lot on my plate and this is something I've already discussed with you. If you'd wanted to dispute it, you could've done so in the relevant thread.
If I tag this version as a release, people will assume that not every push I make is a release, which is not the case.
I'm happy to ping you manually when there's an update, as that's way less work, if that helps.

**Comment by Klaim** [comment]
Alright,

>  I'd appreciate it if you stop pushing this, as I have a lot on my plate and this is something I've already discussed with you. If you'd wanted to dispute it, you could've done so in the relevant thread.

Understood

> I'm happy to ping you manually when there's an update, as that's way less work, if that helps.

If you think every release-commit is worth publishing publicly (it's not clear to me) then yes please send me an email if that's good for you and I'll proceed with packaging as soon as I find the time.

**Comment by mattreecebentley** [comment]
> Alright,
> 
> > I'd appreciate it if you stop pushing this, as I have a lot on my plate and this is something I've already discussed with you. If you'd wanted to dispute it, you could've done so in the relevant thread.
> 
> Understood
> 
> > I'm happy to ping you manually when there's an update, as that's way less work, if that helps.
> 
> If you think every release-commit is worth publishing publicly (it's not clear to me) then yes please send me an email if that's good for you and I'll proceed with packaging as soon as I find the time.

No worries - if you're going to be manually packaging stuff, probably makes sense only to ping you for major releases - TBH there's unlikely to be many significant releases past this point, so I'll ping you if there's something which fixes a bug or adds a significant new feature - if that makes sense.

**Comment by Klaim** [comment]
> so I'll ping you if there's something which fixes a bug or adds a significant new feature - if that makes sense.

Yes it does and working like this is a good compromise IMO.
