### ISSUE TITLE
advance() sometimes returns wrong iterator

### ISSUE THREAD

**Issue by MarcKamradt** [mattreecebentley/plf_colony#5]
I have a colony with a few erased elements, however not the first one. I pass in an iterator to the first element (retrieved via begin()) and a distance of 1.

This leads to the code block starting at line 3013 being executed which leaves the skipfield_pointer as is (skipfield being 0) and also skips the while-loop (--distance will be 0). This will return the same iterator as being passed in, having a distance of 0 instead of 1.

I believe the "--distance" should actually read "distance--" to be correct.

The same is probably true for negative distances however I did not test this.

**Comment by mattreecebentley** [comment]
Thanks for that - have identified the issue and fixed in newly-uploaded ver, also tested for in the test suite, now.
Changed to a do-while loop as distance can't be zero prior.
Let me know if you find anything.
M@
