### ISSUE TITLE
Benchmark results question

### ISSUE THREAD

**Issue by tower120** [mattreecebentley/plf_colony#8]
I'm sure this is just my misinterpretation/misunderstanding.

But. Here http://plflib.org/benchmarks_core2_gcc.htm#rawperformance , at "Post-erasure Iteration Performance" section, as I can see at 100'000 elements with 25% percentage erasure probability, `plf::colony` should perform +/- in pair with `std::vector`. Right? Just to clarify - elements from `std::vector` erased too?

I made small benchmark:

https://github.com/tower120/plf_colony_test
```
int capacity = 100'000;
float erase_probability = 25;
```

I got 350ms for `std::vector`  and 1500ms for `plf::colony`, on i7-4771 with `gcc 7` and +/- the same with `VS 2017 clang/c2` (or whatever compiler they used for open CMake folder).

I could think that this is because of gaps in memory between element positions in `plf::colony`, after random erasure, but...

P.S. Erased `plf::colony` surely iterates faster then full, but speed up is not linear (like with `std::vector`).
P.P.S. For `erase_probability = 90` there is 10 fold difference.

----
P.P.P.S. Maybe you benchmarked in some erase/emplace cycle? Or I, in someway, use it under different conditions?

**Comment by mattreecebentley** [comment]
On 8/09/2017 10:41 a.m., tower120 wrote:
> I'm sure this is just my misinterpretation/misunderstanding.
> 
> But. Here http://plflib.org/benchmarks_core2_gcc.htm#rawperformance , at 
> "Post-erasure Iteration Performance" section, as I can see at 100'000 
> elements with 25% percentage erasure probability, |plf::colony| should 
> perform +/- in pair with |std::vector|. Right? Just to clarify - 
> elements from |std::vector| erased too?

I'm not 100% sure which aspect of the raw performance's you're enquiring 
about, but it sounds like you're enquiring about post-erasure iteration 
performance.
Iteration performance will always be slower with colony than a vector, 
and the graphs on that page show that.
In terms of erasure performance, I'm erasing while doing a single 
iteration over the elements, for all containers. In that context colony 
is fastest.

**Comment by tower120** [comment]
Yes, I'm talking about post-erasure performance. Looking at graphs, I couldn't tell that there is even 2-times difference between `std::vector` and `plf::colony`.

I was curious how "skipfield pattern" could help with non sequential memory access. And it seems that it helps the same as pointers. It almost not help in terms of memory prefetch cache.

P.S. I tried `shrink_to_fit`, and just iteration on full colony (where all elements should be in continuous space) - and it is still 3-5 times slower then vector iteration of the same size (must be due to `operator++` complexity in iterator).

Nevertheless, thank you for clarification of this aspect.

**Comment by mattreecebentley** [comment]
A few notes on your benchmark.
1. You can't run the colony benchmark and the vector benchmark in the same executable and get correct results. I know from my own benchmarking that the mere ORDER of function calls can change the way the compiler decides to inline/not-inline certain code, which can have a detrimental/beneficial effect on various bits of code.
2. 10 runs is not at all adequate for iteration tests. The timing is too quick and you end up gauging nothing. You want at least 100000 runs. 
3. You need a 1 second delay before running the actual benchmark. Otherwise you end up with the overhead from the executable call interfering with the timing.
4. With a typical benchmark you end up discarding the first 10% of results ie. first 10% of runs. Otherwise the cache isn't warmed up.

Clang is not something I've optimized for, as I'm running windows predominantly, and libc++ doesn't run on windows. It sounds like you're not sure which compiler you're running also.

"I was curious how "skipfield pattern" could help with non sequential memory access. And it seems that it helps the same as pointers. It almost not help in terms of memory prefetch cache." This is not correct of course. 
M

**Comment by tower120** [comment]
>1. You can't run the colony benchmark and the vector benchmark in the same executable and get correct results. I know from my own benchmarking that the mere ORDER of function calls can change the way the compiler decides to inline/not-inline certain code, which can have a detrimental/beneficial effect on various bits of code.
> 2. 10 runs is not at all adequate for iteration tests. The timing is too quick and you end up gauging nothing. You want at least 100000 runs.

Applied that, same 5-fold difference...

> 3. You need a 1 second delay before running the actual benchmark. Otherwise you end up with the overhead from the executable call interfering with the timing.

1 second delay between what and what?

> 4. With a typical benchmark you end up discarding the first 10% of results ie. first 10% of runs. Otherwise the cache isn't warmed up.

You mean discard first 10% from 100000 iterations?

>Clang is not something I've optimized for, as I'm running windows predominantly, and libc++ doesn't run on windows. It sounds like you're not sure which compiler you're running also.

I use VS 2017 compiler for Cmake projects (previously they used clang/c2, now I'm not sure). I don't know which std library use clang/c2. Clang/c2 is not exactly the same as Clang.

And also I use gcc 7 (from mingw-w64). Let's focus on gcc.

> "I was curious how "skipfield pattern" could help with non sequential memory access. And it seems that it helps the same as pointers. It almost not help in terms of memory prefetch cache." This is not correct of course.

Why? Skip field indicates how many elements to skip during iteration, doesn't this equal to have pointer to next element, instead?

Or you saying that 
```
std::vector<some_data> list;
std::vector<int> list_indices;
for(int index : list_indices){
    auto& element = list[index];
}
```

Is faster then:
```
std::vector<some_data*> list_ptrs;
for(some_data* data : list_ptrs){
    auto& element = *data;
}
```
?

As I understand, speed-up from  sequential memory access comes mainly from the fact, that adjacent elements fit the cache line (64 bytes). When you read the first element,  the second one  (or at least part of it) also appears in cache.
If between elements is gap more than cache line size - it doesn't matter store them in `std::vector`, or `std::list`.

Here http://coliru.stacked-crooked.com/a/18cf597852ce0229 try to play with `skip` value (and copy paste code on your machine).

P.S. Thou it is definitely faster to skip elements, then iterate them (at least in terms of wasting CPU cycles), I don't see how it can help container element to appear in cache beforehand.

**Comment by mattreecebentley** [comment]
Don't worry about it - I'm not trying to get you to change your results. 
I'm only relaying information.
Thanks,
M
