### ISSUE TITLE
Warning when v4.14 is used with Intel C++ 18.0.1

### ISSUE THREAD

**Issue by MarcKamradt** [mattreecebentley/plf_colony#9]
When using plf_colony 4.14 with the Intel C++ 18.0.1 compiler I get the following warning:

```
plf_colony.h(1918): message #280: selector expression is constant
  						switch (prev_skipfield | (after_skipfield << 1))
  						        ^

```

I haven't really looking into it - just wanted to let know so you can check if that is a false alarm or not.

**Comment by mattreecebentley** [comment]
Compiler bug - the second statement is also a constant, both evaluated prior to the switch for code-clarity's sake. Report to intel if you feel inclined to do so :)
